on:
  rss:
    url:
      - https://sspai.com/feed
      - https://blog.douchi.space/index.xml?limit=5
      - https://geekplux.com/feed.xml?limit=5
      - https://academiaaesthetics.com/feed/
      - https://scottyeung.top/atom.xml
      - http://anotherdayu.com/?feed=rss
      - https://apod.nasa.gov/apod.rss
      - https://www.nasa.gov/rss/dyn/lg_image_of_the_day.rss
      - https://weichen.blog/index.xml
      - https://rsshub.app/zhubai/via?limit=5
      - https://rsshub.app/zhubai/shyrz?limit=5
      - https://rsshub.app/zhubai/bestxtools?limit=5
      - https://rsshub.app/zhubai/dex?limit=5
      - https://rsshub.app/zhubai/shixingcuowu?limit=5
      - https://www.owenyoung.com/atom.xml
      - https://1q43.blog/feed
      - http://www.ruanyifeng.com/blog/atom.xml
      - https://weekly.tw93.fun/rss.xml
      - https://tyingknots.net/feed/
      - https://wangyurui.com/feed.xml
      - https://www.skyue.com/feed/
      - https://newsletter.replay.cafe/rss/
      - https://owlswims.com/feed
      - https://rsshub.app/zhubai/landisland?limit=5
      - https://www.domon.cn/rss?limit=5
      - https://blog.ryouissei.com/feed
      - https://neu-reality.com/feed/?limit=5
      - https://1link.fun/index.xml?limit=5
      - https://kageji.blog/feed/?limit=20
      - https://tianxianzi.me/atom.xml?limit=10
      - https://thirdshire.com/index.xml?limit=5
      - https://blog.liminalnegativespace.xyz/posts/index.xml?limit=5
      - https://www.alrcly.com/feed.xml
jobs:
  request:
    name: Make a HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.CUBOX }}
          method: POST
          body: |
            {
              "type":"url",
              "content":"${{ on.rss.outputs.link }}", 
              "title": "${{ on.rss.outputs.title }}",
              "folder":"Inbox"
            }

